### ISSUE TITLE
Working docker image?

### ISSUE THREAD

**Issue by JerryMartinsonLeviti** [thliebig/openEMS#128]
Hi,

I have MacOS and have been struggling to get it to compile.  I went through all the issues and stuff and can't get it to work.  One thing from going through the process and looking at other's works is that it seems that this tool is great but depends on a lot of moving parts that are beyond openEMS direct control.

I suggest a way around this issue: Create a working Ubuntu docker image with Octave/Python etc... that can forward X out to an X server.  That way it can work in windows, unix, mac without all of us stumbling over our specific computer setup.

Has anyone done this yet?

**Comment by MrHighVoltage** [comment]
Yes, openEMS is included in our [IIC-OSIC-Tools](https://github.com/iic-jku/iic-osic-tools) Docker container, that is basically a complete collection tools for open-source IC Design. So maybe this is an overkill for you, but openEMS is included and the container is ready to run with X-forwarding or a VNC-Server.

If that is too much bloat for your application, you can use our build-setup to build your own container and remove everything you do not need. But basically, this should be quite easy, as openEMS is included in the Ubuntu-Packages.
