### ISSUE TITLE
openems.de webpage is down

### ISSUE THREAD

**Issue by michal777** [thliebig/openEMS#41]
I can't access openems webpage. What's wrong? Will it come back soon?

**Comment by thliebig** [comment]
The host has major issues. I don't know why. All attempts to fix it over the last couple of weeks did not help. Plans to move the page are under way, but I don't know how long this will take.

**Comment by brnold** [comment]
Do you have the tutorials hosted/available somewhere else?

**Comment by thliebig** [comment]
The tutorials are all inside the binary and source packages and on github of course...

**Comment by odo2063** [comment]
Wieviel Webspace bräuchtest du denn? 

How much Webspace would you need?

**Comment by thliebig** [comment]
I think this can be closed now. The new site is online. We just need to think about a new/better documentation. The old wiki will remain a static page now...
