### ISSUE TITLE
Try downloading source and/or tutorial files gives https error

### ISSUE THREAD

**Issue by odo2063** [thliebig/openEMS#42]
https://www.openems.de/gitweb/?p=openEMS.git;a=blob_plain;f=matlab/Tutorials/Simple_Patch_Antenna.m;hb=refs/heads/master

![screenshot_2018-12-14 hinweis hint](https://user-images.githubusercontent.com/15078667/50013977-effeed80-ffc2-11e8-9aa9-57c850d91e68.png)

**Comment by odo2063** [comment]
http://openems.de/index.php/Tutorial:_Simple_Patch_Antenna.html

The example file produces the error, for example.

**Comment by thliebig** [comment]
Should be all fixed, please confirm...
