### ISSUE TITLE
Simulation end criteria

### ISSUE THREAD

**Issue by gabriel-tenma-white** [thliebig/openEMS#57]
I have a simulation of a magnetic loop antenna where the end criteria of -50dB energy is sometimes reached prematurely (depending on parameters like excitation frequency). Looking at the dump of current density there are still plenty of current in the antenna structure at the end. I'm guessing the energy calculation is only based on total E fields, whereas this antenna can store most of its energy in the magnetic field at some time instants. Is it true that the energy calculation only looks at E fields?

**Comment by thliebig** [comment]
No energy stored in E- and H-fields is considered. But only vacuum is assumed.
