### ISSUE TITLE
Issue with recalling the run function

### ISSUE THREAD

**Issue by khashabri** [thliebig/openEMS#59]
Hello guys, 
the following line in the [run function](https://github.com/thliebig/openEMS/blob/cc5a709e743fa246474c1d071a8beb0f77027a82/python/openEMS/openEMS.pyx#L413) (python interface) is useless and it causes an error when calling `run(..., cleanup=True)` multiple times in the same script.
https://github.com/thliebig/openEMS/blob/cc5a709e743fa246474c1d071a8beb0f77027a82/python/openEMS/openEMS.pyx#L431 Solution: this line should be deleted, and the c++ file should be recompiled.

**Comment by thliebig** [comment]
Well yeah, makes sense. Do you want to commit a patch and pull request for it? ;)
