### ISSUE TITLE
openEMS.sh

### ISSUE THREAD

**Issue by thomaslepoix** [thliebig/openEMS#73]
Hi Thorsten!

What is the point of the openEMS.sh script?

```sh
#!/bin/bash

#clear LD_LIBRARY_PATH
export LD_LIBRARY_PATH=

#get path to openEMS
openEMS_PATH=`dirname $0`

#execute openEMS
exec $openEMS_PATH/openEMS $@
```

Since it does nothing else than just running the openEMS binary, I think we should remove it and make `invoke_openEMS.m` call the `openEMS` binary instead. May is there still a reason that I can't see?

Best regards,

**Comment by thliebig** [comment]
I think Octave used to set wired LD_LIBRARY_PATH definitions making openEMS find the wrong binaries.
That is the reason for this file. I'm not sure if this is still necessary but it might highly depend on the system and Octave version and such...
