### ISSUE TITLE
plotRefl.m not Matlab compatible?

### ISSUE THREAD

**Issue by srcejon** [thliebig/openEMS#74]
openEMS 64-bit v0.0.35 on Windows 10 with Matlab R2020b

Trying to run the patch antenna example (first time user). It fails with:

Error: File: plotRefl.m Line: 120 Column: 19
Indexing with parentheses '()' must appear as the last operation of a valid indexing expression.

Which corresponds to the following line:

llegend = num2str(port.f(lowerind)(1)/1e6, ffmt);

(And there are a few other lines in that file with similar syntax - the Matlab editor says Cannot call or index into a temporary array)

I think this syntax for cascaded indexing is only supported in Octave, not Matlab.

If I use temp variables to work around it, I then get:

Error using linspace (line 22)
Inputs must be scalars.

Which is from:

linspace(-ImZ, ImZ, 256)

Where ImZ =  0.0000 + 1.0000i   0.0000 + 2.0000i   0.0000 + 5.0000i   0.0000 + 2.0000i

Again, looks like this is something supported by Octave, but not Matlab.

**Comment by thliebig** [comment]
That might very well be the case. I do not have Matlab available. Maybe you can find a solution that works for Matlab and hopefully we can find something that works for both
