### ISSUE TITLE
In openEMS.sh $@ should be in quotes

### ISSUE THREAD

**Issue by yurivict** [thliebig/openEMS#77]
This line https://github.com/thliebig/openEMS/blob/master/openEMS.sh#L10 should be:
```
exec $openEMS_PATH/openEMS "$@"
```

Otherwise it messes up arguments with spaces.

**Comment by thliebig** [comment]
I agree, can you create a pull request with a fix?

**Comment by yurivict** [comment]
https://github.com/thliebig/openEMS/pull/80
