### ISSUE TITLE
Please use sh instead of bash

### ISSUE THREAD

**Issue by yurivict** [thliebig/openEMS#79]
This line https://github.com/thliebig/openEMS/blob/master/openEMS.sh#L1 should be replaced with
```
#!/bin/sh
```

because Bash is an extra-dependency on systems which don't have Bash installed by default (ex. *BSD).

**Comment by thliebig** [comment]
Sounds like a wired setup to have, but okay, please create a pull request, maybe together with  #77

**Comment by yurivict** [comment]
https://github.com/thliebig/openEMS/pull/80
