### ISSUE TITLE
where is the harminv.exe, i can not find it.

### ISSUE THREAD

**Issue by ihaveusernam** [thliebig/openEMS#86]
when i use the 
      [freq,decay,Q,amp,phase,err]=harminv( u, t(2)-t(1), 0, 1e9 );

matlab displays an error：

 "D:\CODE _TEST\dashijie\paper\FDM\FDMC++\openEMS-master\matlab\..\harminv.exe" -t 1.6683e-11 0-1000000000 < "C:\Users\liu\AppData\Local\Temp\tpfb124c08_746d_447d_be64_c652ab3f21fb"
exit status: 1
output: '"D:\CODE _TEST\dashijie\paper\FDM\FDMC++\openEMS-master\matlab\..\harminv.exe"' Not an internal or external command, nor a runnable program or batch files.

**Comment by thliebig** [comment]
I just checked, our windows binary download contains harminv as expected. It looks like you build openEMS yourself?
Then you have to download and/or build harminv too...
