### ISSUE TITLE
Problem Registering on forum

### ISSUE THREAD

**Issue by Dianebonk** [thliebig/openEMS#91]
Hello, 
I have a problem registering on your forum. To finish the inscription I have to put the latest version of OpenEMS.
I put: 
v6.0
................

But nothing worked for me.
Did anyone know the latest version. I want to connect and ask my questions.

**Comment by Dianebonk** [comment]
![register issue](https://user-images.githubusercontent.com/98905793/175973946-f963f59f-e264-43b6-b5e8-6b39f372e03e.jpg)

**Comment by thliebig** [comment]
Please visit the [openEMS website](https://openems.de/start/) to find the answer...
