### ISSUE TITLE
Cant install the octave integration: error: 'isOctave' undefined near line 17, column 4

### ISSUE THREAD

**Issue by fcolecumberri** [thliebig/openEMS#92]
I am running on linux, I have already added the:

```octave
addpath("/usr/local/share/openEMS/matlab/");
```

to the `.octave` file and then execute the `setup` instruction, I only get the next error:

```txt
error: 'isOctave' undefined near line 17, column 4
error: called from
    setup at line 17 column 4
```

Any help?

**Comment by ra1nb0w** [comment]
same issue; have you found a fix? thanks

**Comment by fcolecumberri** [comment]
> same issue; have you found a fix? thanks

No

**Comment by ra1nb0w** [comment]
resolved running the following command in Octave
```
addpath('/usr/share/CSXCAD/matlab');
addpath('/usr/share/openEMS/matlab');
savepath
```
then you can exit and re-open Octave and `setup` works fine.
